### ISSUE TITLE
HTML version and HTML template

### ISSUE THREAD

**Issue by Sirtea** [retext-project/retext#163]
Hi,

Should be desirable to change html template and html version generator, so it could be viewed same as my webpage; perhaps, a checkbox to generate HTML5 and a config option pointing to a template file with static CSS files.

Regards

**Comment by mitya57** [comment]
There was a tool for this in earlier ReText versions (it was called “webpages generator”), however I dropped that code because I didn't have time to maintain it, and because better alternatives exist.

You can try [Sphinx](http://sphinx-doc.org/) for reStructuredText, [MkDocs](http://www.mkdocs.org/) for Markdown, and also [Pelican](http://blog.getpelican.com/) or [Nikola](https://getnikola.com/) for both formats.

**Comment by Sirtea** [comment]
Yes, I know pelican as it's the tool I'm using right now.
The idea was to put the same html theme in retext, so the preview tab looked the same as once rendered in pelican.

For example, geany markdown plugin allows to specify base HTML with a placeholder, so the html generated can fit in there

**Comment by Tamriel** [comment]
My [fork](https://github.com/Tamriel/retext) does the preview with Jekyll. However, I like the idea of switching to Pelican.

**Comment by farseerfc** [comment]
+1 for pelican. (Just because my blog is using it)

**Comment by mitya57** [comment]
Being a static site generator is out of scope for ReText. There are many dedicated tools that do this job very well (see my comment above), we won't be able to compete with them anyway. With some scripting you can integrate them into ReText using the [export extensions](https://github.com/retext-project/retext/wiki/Export-Extensions) mechanism.

So I am closing this issue.
