### ISSUE TITLE
Issue with bullets

### ISSUE THREAD

**Issue by moshpirit** [retext-project/retext#186]
When we write a list with bullets, and we want to get out of this list, the bullets keep being shown no matter how many *enter* we have pressed. It would be nice if the empty bullets would be erased when we press *enter* twice.

Steps: 

1. write `- Bullet 1`
2. write `- Bullet 2`
3. press *enter*
4. press *enter*

bullets for 3. and 4. should disappear but they don't.

**Comment by mitya57** [comment]
You can use Ctrl+Enter to prevent ReText from creating a new list item.

I will now push a commit that will make it not start a new item if previous one was empty, but I don't want to remove already existing text — what if the user wanted to have exactly such a line?

**Comment by moshpirit** [comment]
Then the user can input one "-" and that's it, isn't it?

**Comment by mitya57** [comment]
I still don't want to delete the existing text. Maybe it's a code block where the spacing is relevant? :)

To be honest I never really liked the current list auto-completion code because it is annoying when I want to create a list item with multiple lines. So I was thinking about removing this logic altogether and replacing it with something much simplier (i.e. only copy the whitespace to new lines).

**Comment by moshpirit** [comment]
>Maybe it's a code block where the spacing is relevant?

I'm sorry I didn't understand you :( 

IMO auto-completion is something really useful, just a bit annoying if it put too much code (e.g. the bullets I told you above). It is the only thing that I don't like about the current configuration. ReText is very helpful for me in this aspect.

**Comment by mitya57** [comment]
Ok, after thinking a bit more about it, I implemented the behavior you suggested. Please test :)
