### ISSUE TITLE
no Code Highlighting

### ISSUE THREAD

**Issue by retsyo** [retext-project/retext#241]
I am using the ReText 6.1.0 (Git) on Anaconda 64 bits on Win7. The code from https://sourceforge.net/p/retext/wiki/markdown_syntax/ does not render highlighted text

    :::python
    import abc

    #!/usr/bin/python
    import abc

**Comment by retsyo** [comment]
any hints?

Python 3.4.4 |Anaconda 2.3.0 (64-bit)| (default, Feb 16 2016, 09:54:04) [MSC v.1
600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> pygments.__version__
'2.1.3'

**Comment by mitya57** [comment]
Hi, you need to enable the built-in `codehilite` extension. Just open the preferences dialog, add `codehilite` to the list of Markdown extensions, and open a new tab so that the change takes effect.

You can also specify some options to that extension if you want, see [the documentation](http://pythonhosted.org/Markdown/extensions/code_hilite.html) for details.
