### ISSUE TITLE
Error: ReText needs PyMarkups 2.0 or newer to run.

### ISSUE THREAD

**Issue by RishabhMalviya** [retext-project/retext#292]
I just installed and upgraded to the latest version of PyMarkdown, yet I continue to get this error whenever I try to run ReText from the command line. Running this on Ubuntu 16.04 LTS.

Here's what I did:
```
$ sudo -H pip3 install Markdown --upgrade

Collecting Markdown
  Downloading Markdown-2.6.8.tar.gz (307kB)
    100% |████████████████████████████████| 317kB 303kB/s 
Building wheels for collected packages: Markdown
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /root/.cache/pip/wheels/85/a7/08/33ee5cd488d0365d8bed79d1d4e5c28dd3fbfc7f6d0ad4bb09
Successfully built Markdown
Installing collected packages: Markdown
  Found existing installation: Markdown 2.6.6
    Not uninstalling markdown at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed Markdown-2.6.8
```

Then, when I run ReText on a `.md` file from my home folder, I get this message:

`Error: ReText needs PyMarkups 2.0 or newer to run.`

**Comment by mitya57** [comment]
Hi,

* First of all running `pip` or `pip3` as root is a bad idea because it may mess up with the system packages and break other software. I always recommend using `--user` instead.
* Then, you seem to be having `python3-markups` from Ubuntu repositories installed. If you want to run ReText 6 or newer, please run `pip3 install --user --upgrade Markups`, this will install the latest PyMarkups.
