### ISSUE TITLE
no tool button bitmap displayed under win10-x64.

### ISSUE THREAD

**Issue by zaazbb** [retext-project/retext#343]
1, all tool buttons disp as blank,  image as below.
![image](https://user-images.githubusercontent.com/5773083/32831918-d5f0b9ec-ca34-11e7-909e-8162e792648e.png)

2, can install use pip, because can not find pyenchant's amd64 wheel.
maybe remove 'pyenchant' from 'requires' list in setup.py can resolve this problem.

**Comment by mitya57** [comment]
Please use the [official tarball](https://pypi.python.org/packages/2a/ba/581591a8a8d48d02236b57633ae5f55247424885e143fe1d21fba904a1ed/ReText-7.0.1.tar.gz), it contains all the needed icons.
Or, alternatively, download the [icons tarball](https://github.com/retext-project/retext/archive/icons.tar.gz) and unpack it into your `icons` directory.

The pyenchant dependency is already optional since commit a7a43501bd4d7db716caa5e0111de8c7bb7bd3d5.
