### ISSUE TITLE
Doens't start on ArchLinux

### ISSUE THREAD

**Issue by artemanufrij** [retext-project/retext#386]
Installed by command: `pacman -S retext`

error when I try to start it:
``` bash
Traceback (most recent call last):
  File "/usr/bin/retext", line 23, in <module>
    import markups
  File "/usr/lib/python3.7/site-packages/markups/__init__.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by axionl** [comment]
What is the version of this package?

**Comment by artemanufrij** [comment]
@axionl 
`7.0.3`
https://www.archlinux.org/packages/?q=retext

**Comment by mitya57** [comment]
Hi @artemanufrij!

You should report this bug to the ArchLinux package maintainer.

PyMarkups should depend on the package which provides pkg_resources module. This dependency was introduced in the last release of PyMarkups.

**Comment by axionl** [comment]
@artemanufrij 

The `python-markups>=2.0.0` has been depended, you can try to find this on `/usr/lib/python3.7/site-packages` .  Please check your python environment, one possible reason is that you install this package or `python` by `pip` at last time.

**Comment by artemanufrij** [comment]
Hey guys, thank you for your feedback... I will try it tomorrow.

**Comment by artemanufrij** [comment]
`python-markups-3.0.0-4` was already installed.

**Comment by mitya57** [comment]
The problem is not with retext → python-markups dependency.

The problem is that python-markups should depend on [python-setuptools](https://www.archlinux.org/packages/extra/any/python-setuptools/), because _that_ package provides `/usr/lib/python3.x/site-packages/pkg_resources/` which is needed for python-markups.

I will now update upstream metadata to include setuptools dependency.

**Comment by artemanufrij** [comment]
Now it works as expected! thank you guys!
