### ISSUE TITLE
[FR] Option for hidding menu bar [ctrl+m]

### ISSUE THREAD

**Issue by artemanufrij** [retext-project/retext#392]
It would make Retext closer to native KDE apps.

**Comment by mitya57** [comment]
Do you mean the *menu* bar (File, Edit, Help) or the *tool*bars (with icons) like in #395?

**Comment by artemanufrij** [comment]
File Edit Help

**Comment by mitya57** [comment]
Due to how Qt works, if the menu bar is hidden, you won't be able to use any shortcuts, including Ctrl+M to bring it back. So it would be non-trivial to implement.

If you want to save space, then I can suggest you to use global menus, they are available for both Plasma and GNOME, and don't have such drawback.
