### ISSUE TITLE
ReText doesn't remember visible state of menu bars

### ISSUE THREAD

**Issue by artemanufrij** [retext-project/retext#395]
Reproduce:
1. Open ReText
2. Right click on the menu bar and disable both menu bars (format and files)
3. Restart ReText

Expected: menu bars aren't visible

Currently behaviour: both bars are visible

**Comment by mitya57** [comment]
There is a configuration option for this too. Add `hideToolBar=true` to the configuration file. See my comment in #393 for details on the configuration file.

**Comment by artemanufrij** [comment]
@mitya57 I mean an other behavior. If you disable a menu bar so it will be visible again after restart. `hideToolBar=true` hide whole tool bar, so far I understood.

**Comment by mitya57** [comment]
There are three toolbars: File, Edit and Search. You can enable or disable them individually by right-clicking on any of them or on the menu bar.

There is a way to disable all of them persistently, using the configuration file. There is no way to disable only one of them persistently (e.g. only the Edit toolbar) because two toolbars consume as much space as the single one.

Please be more verbose on what you want.

**Comment by mitya57** [comment]
Sorry, this sounds like a too narrow use case. I want to keep the app as lightweight as possible, so I don't want to introduce such features.

**Comment by dessalines** [comment]
I just ran into this too. Makes sense to me that if I hide the toolbars, and restart retext, I want to make sure they're hidden when I restart it. It could be added in the settings panel too for persistence.
