### ISSUE TITLE
automatic reload upon external editing

### ISSUE THREAD

**Issue by clarkevans** [retext-project/retext#456]
Thanks for such a lovely editor.  Even so, in most cases, I'd love to use reText only as a viewer (I'd like to use vi).  Could there be an option to simply update the formatted output if the file changes?

**Comment by mitya57** [comment]
It should be already the case! When a file updates locally, ReText will reload both the editor and preview parts.

If it does not work for you, please let me know what ReText version and what OS you are using.

**Comment by clarkevans** [comment]
Hi.  So, it's 7.0.1 on Ubuntu 18.04 from system packages.  Rather than reloading the file, what I get is a popup message that says: "This file has been deleted by other application. Please make sure you save the file before exit."  I didn't see an option to reload when the file changes.

**Comment by mitya57** [comment]
I just tried with ReText 7.0.1 and vim and the file reloads correctly.

If such a message is displayed for you it means that ReText cannot find the file on disk, i.e. this block is active:

https://github.com/retext-project/retext/blob/f0e47e3f6fb4331e35eb331b5e0356c11f5b3d32/ReText/window.py#L1077

Does the same thing happen with other external editors, e.g. nano or gedit?

Does the full path to file have any unusual characters? If yes, can you try with an ASCII file path like `/tmp/foo.md`?

**Comment by clarkevans** [comment]
So, the file name is boring.  It reloads file with other editors, like pico. So, this seems to be `vim` specific behavior on Ubuntu 18.04 -- even if I use standard vim configuration. Interesting.

**Comment by mitya57** [comment]
Looks like with certain options vim renames the current file `foo` to `foo~` and then writes a new `foo` file. Then there is a race condition. If ReText checks the file existence before the new file is created, it will think it is deleted.

There is a [`backupcopy` option](http://vimdoc.sourceforge.net/htmldoc/options.html#'backupcopy') in vim to configure this behavior. If you set it to `yes` it will *copy* `foo` to `foo~` rather than renaming. I think this should fix the issue.

According to the docs `yes` should be the default on Unix, but it looks like it actually defaults to `auto` on Debian/Ubuntu.

**Comment by mitya57** [comment]
I should also mention that you can use `inotifywait -m` to monitor what the other editors are doing with your files.

**Comment by mitya57** [comment]
I am closing this bug. Support for simultaneous editing with multiple editors is not a top priority, and we support it to a certain extent anyway — it’s vim specific behavior that it moves a file, and this behavior can be changed in vim.

Anyway, pull requests to improve this will be welcome.
