### ISSUE TITLE
Running ReText with Adwaita Dark Theme

### ISSUE THREAD

**Issue by Lonerider2010** [retext-project/retext#492]
When running ReText with adwaita dark theme, the current line has a yellow background, where the text is shown in white, so it is not readable. My environment: Raspbian Buster with XFCE, adwaita-qt and qt5ct installed.

**Comment by mitya57** [comment]
Sorry for the late reply.

In the configuration file, we have a section that allows you to tweak colors as you want. I suggest you to set `currentLineHighlight` to something dark.

Please see https://github.com/retext-project/retext/blob/master/configuration.md#color-scheme-setting for the documentation.

I am keeping this bug open because having a default dark configuration is a valid feature request. If you manage to write one, please share it :)

**Comment by Moini** [comment]
I find the white-on-white text in the preview pane even more problematic. Worked around by using the web renderer.

**Comment by mitya57** [comment]
@Moini Are you using reStructuredText? I am asking because with Markdown Adwaita-Dark seems to work perfectly:

![Screenshot](https://user-images.githubusercontent.com/1381584/109429491-00b5a580-7a0d-11eb-9f92-5c30e87daeb3.png)

Anyway, for reStructuredText using WebKit or WebEngine renderer is a good idea. Glad to hear that it fixed the issue. If there are remaining issues please let me know.

**Comment by Moini** [comment]
Yes, I was using reST.

Well, 'fixed' is maybe the wrong word for it... I'd call it a workaround, unless you intend to scrap the default mode and replace it by the web renderer - in that case, it's of course not necessary that it works in default mode, too.

**Comment by mitya57** [comment]
@Moini The linked commit in pymarkups should make reStructuredText rendering better for both WebKit and non-WebKit renderers.

Maybe you can test pymarkups from master before I make a new release?

**Comment by Moini** [comment]
Mmh - I just downloaded the zip file from here: https://github.com/retext-project/retext/archive/master.zip, unpacked it into my /tmp folder, ran `python3 retext.py`, and removed the check mark from the web renderer box.

Using the example text from here: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html

it looks like this:

![2021-03-02_20-57](https://user-images.githubusercontent.com/3240233/109707172-245a2680-7b9a-11eb-9d14-cbf7b0e07698.png)

**Comment by mitya57** [comment]
@Moini Please try this command:

    pip3 install --user --upgrade https://github.com/retext-project/pymarkups/archive/master.tar.gz

The fix I applied was not in ReText itself, but in [pymarkups](https://github.com/retext-project/pymarkups) — the helper library used by ReText. You updated ReText itself, so you did not get the fix.

But if you try master versions of *both* ReText and pymarkups, you should get an even better experience: ReText commit 5343c00b40a6c163 improves the color of links in dark themes.

I am going to make new releases of both pymarkups and ReText soon, and any feedback is welcome: if there are remaining bugs related to dark theme, I may fix them too.

**Comment by mitya57** [comment]
I have released new versions of both pymarkups and ReText now. You can upgrade e.g. by using this command:

    pip3 install --user --upgrade Markups ReText

These releases should solve most issues related to dark themes. As a bonus, synchronized support will now work for reStructuredText.
