### ISSUE TITLE
Bullet list without title don't work.  Debian - ReText 7.1.0 (using PyMarkups 3.0.0)

### ISSUE THREAD

**Issue by buserror** [retext-project/retext#511]
On debian testing, retext has a problem with bullet lists that are not preceded by a title:
* this
* does not
* work

## while:
![2020-05-29-093920_1007x575_scrot](https://user-images.githubusercontent.com/157201/83239818-65975300-a190-11ea-890d-9c5a63aad82f.png)

* this
* will

**Comment by mitya57** [comment]
Hi!

This is expected behavior. The Markdown syntax rules [say](https://daringfireball.net/projects/markdown/syntax#block):

> […] block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines […]

And lists are definitely block level elements.

Please also see https://github.com/Python-Markdown/markdown/issues/413#issuecomment-106990421 and the previous comment for an explanation of this behavior.

Many other Markdown parsers behave [in the same way](https://johnmacfarlane.net/babelmark2/?normalize=1&text=Some+text%0A*+Item+1%0A*+Item+2).
