### ISSUE TITLE
Line highlighting does not highlight full line-wrapped lines

### ISSUE THREAD

**Issue by internationils** [retext-project/retext#516]
Running 7.1.0 with Qt 5.12.8 under latest Ubuntu Focal... if I have the current line highlight option on, then with text wrapped only the one line not the several lines (i.e. line beginning to EOL) are highlighted in yellow. Commented on in https://github.com/retext-project/retext/issues/513#issuecomment-640855707

I think this option would make sense, as I want to see what is on one line and what is not, currently forcing me to turn line numbering on to see what is on one line and what is wrapped. I would make it optional, not default beaviour.

**Comment by nihillum** [comment]
Hello, I found a way to fix this issue. 
But I think I found another (possible) minor bug regarding the line highlighting.
It seems that when toggling the setting it is not immediately enabled/disabled (like it happens instead for line numbers), but only after a change in the cursor position.
Is this the expected behavior?
I'm new to the code base so I don't know where to look to try fixing this second problem.
