### ISSUE TITLE
Retext incorrectly shows text as italic (see attached code fragment for details) in editor pane

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#529]
Steps to reproduce:

1. Enter the following Markdown code in the ReText editor

      Here will be a star as inline code block `*` with some text after it which is rendered as italic because of some bug and interpreting other star in the last element - `*`. This text has normal weight as expected.

1. View this code in the editor

Expected results:
* text has normal weight in editor pane

Actual results:
* text has italic part in editor pane - see screenshot below:

  ![](https://launchpadlibrarian.net/501070076/retext-bug.png)

Link to downstream bug-report: https://pad.lv/1898897 .

**Comment by mitya57** [comment]
Thank you for the report!

This is a valid bug, but will be difficult to fix. I will need to think how to do it.

**Comment by mitya57** [comment]
I have a fix in `wip/highligher` branch, can I ask you to test it (see the linked commit)?

It fixes this bug, but unfortunately now it may *not* highlight some valid markup between code blocks. E.g. in this line
```markdown
`*` *real italic* `*`
```
the `*real italic*` part will be not highlighted, because the wrong pairs of asterisks are matched with each other. But I believe we can live with that.

**Comment by N0rbert** [comment]
Thanks, this proposed fix works as expected. 

>the *real italic* part will be not highlighted, because the wrong pairs of asterisks are matched with each other. But I believe we can live with that.

I agree.
