### ISSUE TITLE
Files saved with incorrect encoding

### ISSUE THREAD

**Issue by Alezy80** [retext-project/retext#549]
When reading files Utf-8 with BOM (this is normal for Windows) the encoding detected as `UTF-8-SIG`. The text seems read correct, but file saved with `windows-1251` encoding (I have Russian Windows). On next file open encoding correctly determined as `windows-1251`, but encoding change on save shouldn't happen. 

And also the code `self.editBox.document().setProperty("encoding"...)` is executed only on file open, but in new created file this property is `None`, and file saved with `windows-1251` encoding though I have `defaultCodec=utf-8` in ini file.

I think that default encoding must be set as `utf-8` on all platforms, without need of ini file modification.

**Comment by mitya57** [comment]
Hi!

I pushed two commits which should fix both issues you mentioned (not handling UTF-8-SIG and not using `defaultCodec` for new files). Can you please test version from master?

> I think that default encoding must be set as `utf-8` on all platforms, without need of ini file modification.

I will need to rewrite encodings-related code because of Qt 6, which no longer has QTextCodec. Maybe it will happen together with that rewrite.
