### ISSUE TITLE
Image overlaps with text

### ISSUE THREAD

**Issue by matkoniecz** [retext-project/retext#563]
`<a href=""><img src="images_for_description/prototype_delivered_cropped.jpg" width="100%"/></a><br/>`

expected as on GitHub: https://github.com/matkoniecz/lunar_assembler#in-action

![screen01](https://user-images.githubusercontent.com/899988/119625117-24209e80-be0a-11eb-8bb2-8ce5d82fbe72.png)

ReText rendering on Lubuntu 20.04

![screen02](https://user-images.githubusercontent.com/899988/119625210-3d294f80-be0a-11eb-9180-5ace3b0a515c.png)

Qt version 5.12.8.

ReText 7.2.1 (using PyMarkups 3.1.1)

I looked at https://github.com/retext-project/retext/wiki/FAQ

I am willing to run debug versions and test possible solutions, though I am unlikely to be able to solve the problem

**Comment by mitya57** [comment]
The problem here is that `100%` is not a valid value for `width` attribute. Let me quote the [HTML specification](https://www.w3.org/TR/html52/semantics-embedded-content.html#sec-dimension-attributes) (emphasis mine):

> The `width` and `height` attributes on `<img>`, `<iframe>`, `<embed>`, `<object>`, `<video>`, and […] `<input>` elements may be specified to give the dimensions of the visual content of the element […], **in CSS pixels**. The attributes, if specified, must have values that are **valid non-negative integers**.

Qt's HTML parser, if the node has a `width` attribute, first sets the image width to a negative value (-2), and then tries to parse the attribute. If the attribute cannot be parsed as a number, then it remains negative and the rendering is broken. Here is the relevant code fragment:
https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/text/qtexthtmlparser.cpp?h=5.15.2#n1641

If you want to specify the width in percents, you should use CSS (`style="width: 100%"`) rather than plain `width="100%"` attribute. However, unfortunately, Qt's built-in parser [does not support that](https://doc.qt.io/qt-5/richtext-html-subset.html#css-properties) too.

So in addition to changing the markup, I recommend you to enable the WebKit or WebEngine renderer. You can do it from the “Edit” menu in ReText. If it is not available, try running `pip install PyQtWebEngine`.

**Comment by matkoniecz** [comment]
Thanks for debuging what I did wrong! Is it normal that WebKit has ant-sized font?

Even regular was tiny on large-resolution screen and WebKit is getting unreadable for me. But thanks to Editor->change editor font (and preview font) it was fixable.

I see no other options except WebKit, `pip install PyQtWebEngine` was done already. I did `pip install --upgrade --user PyQtWebEngine`

![screen02](https://user-images.githubusercontent.com/899988/120004249-d4db9900-bfd6-11eb-9ec1-0f47124f8940.png)
![screen03](https://user-images.githubusercontent.com/899988/120004255-d60cc600-bfd6-11eb-9161-02e58593de11.png)


Thanks for this software!

**Comment by mitya57** [comment]
> Is it normal that WebKit has ant-sized font?

Yes, both WebKit and WebEngine treat font sizes in a different way than QTextEdit (which is used in editor and in default preview).
You can use “Change preview size” to adjust it permanently, or Ctrl + mouse wheel scroll, to zoom in/out in the current session.

> I see no other options except WebKit, `pip install PyQtWebEngine` was done already.

When both WebKit and WebEngine are available, ReText prefers WebKit. This is because early versions of Qt WebEngine were unstable and could sometimes crash. I will probably change it in a future release, because Qt WebKit is seemingly dead and Qt WebEngine is an active project.

> I did `pip install --upgrade --user PyQtWebEngine` This enabled "Web engine (Chromium)" renderer.

This probably upgraded the whole PyQt, and QtWebKit became unimportable. In any case, I think there should be little difference between WebKit and WebEngine with regards to font sizes.
