### ISSUE TITLE
table alignment

### ISSUE THREAD

**Issue by carlos-mazieri** [retext-project/retext#608]
When using the colon character for alignment the table is not shown (the borders do not appear)

Example,  in table below the borders do not appear:

|Command line|
|:--------|
|./test_AML.sh inject --device GPU --event "Reset Required" --device-index 1|

**Comment by mitya57** [comment]
Thank you for the report.

It is actually a bug in QTextEdit, not in ReText. It happens because when you use colon, Qt produces the following HTML code:
```html
<th style="text-align: left;">Command line</th>
```

And it looks like when an element has `style`, global CSS is not applied to it. I have forwarded this to Qt developers: https://bugreports.qt.io/browse/QTBUG-111285.

As a workaround, you can enable Qt WebEngine previewer (from the ‘Edit’ menu), it does not have this bug.

**Comment by carlos-mazieri** [comment]
Thank you.
Carlos
