### ISSUE TITLE
Strange problem rendering '$'s

### ISSUE THREAD

**Issue by mderouss** [retext-project/retext#626]
Hi there,

I'm trying to write this : 

Most bloggers aren't asking hard questions about the underlying technologies if they can get a sexy looking thing going for a few $$$ ( or no $$$ ). 

You may agree or disagree :) . But my problem is that the dollars and the text between them are not rendered correctly in the HTML preview, no matter which renderer I choose, and no matter how I try to escape the dollar signs. This wasn't an issue using the same text in another tool ( ghostwriter ).  I have a feeling that some math extension might be interfering here, but there's no way to turn off math stuff that I can see.

**Comment by mitya57** [comment]
Yes, `$$` is syntax for math blocks (see https://github.com/retext-project/retext/wiki/Math).

You can either disable math completely by adding the following line to the beginning of your file:
```
<!-- Required extensions: remove_extra -->
```

or you can use `&dollar;` instead of a raw dollar sign.

Also you can insert a zero-width space (U+200B) between the dollars: $&#x200B;$&#x200B;$.
