### ISSUE TITLE
problem with export footnote in PDF

### ISSUE THREAD

**Issue by rcspam** [retext-project/retext#651]
Hi,

Thanks for your very good word.

Version: ReText 8.0.2 (with PyMarkups 4.0.0)

A  text with  footnotes:

```
blabla [^1] and  Bloblo [^2].

[^1]:first note. [](#note1)
[^2]: second note. [](#note2)
 
<a id="note1"></a>
<a id="note2"></a>
```
All works fine in the MD file.
But the return to the num in the text fails in the exported PDF file.

Cheers

**Comment by mitya57** [comment]
Thank you for the bug report!

It is a problem in Qt library. I have reported it to the Qt developers here: https://bugreports.qt.io/browse/QTBUG-132489.

As a work-around, you can enable the WebEngine previewer. Then PDFs are generated also with WebEngine, and both links in PDF work. I recommend enabling WebEngine anyway, since it supports all kinds of HTML unlike the default previewer, which only supports a subset.
