### ISSUE TITLE
pandoc support

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#7]
please add support for [http://johnmacfarlane.net/pandoc/](pandoc's extension) to markdown, since it is a very convenient lot of additions.
Maybe some other extensions could be added, but I am not familiar with the other so that I can only recomment Pandoc's one.
Note: There is already a pandoc wrapper for python by Kenneth Reitz: https://github.com/kennethreitz/pyandoc

Reported by: codronm

Original Ticket: [retext/tickets/7](https://sourceforge.net/p/retext/tickets/7)

**Comment by onlyjob** [comment]
I also would very much like to have Pandoc support in Retext. Maybe Pandoc has matured since 2015 but these days it is an awesome Markdown converter with so many features: https://pandoc.org/MANUAL.html#pandocs-markdown

For now because of Pandoc support I have to use Ghostwriter but Retext interface is better so it might be good to introduce Pandoc support for feature-parity with Ghostwriter.

Thanks!
